
project_id = "bcyfmeosiighdamisgwp"

[functions]
[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.ai-completion]
verify_jwt = true
